import { NextPage } from 'next'
import Head from 'next/head'
import { ChButton } from "cheetah-react-ui";
import SeasonAnime from "../../app/components/Home/SeasonAnime";

const Anime: NextPage = () => {
    return (
        <>
            <Head>
                <title>Anime</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                Anime
                <ChButton mode='danger' label='Тык' />
            </div>
        </>
    )
}

export default Anime
