version: '3'

services:
  db:
    image: postgres:14.3-alpine
    env_file: .env
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
  web:
    build: .
    command:  python /usr/src/anime_media/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/anime_media
    ports:
      - 8000:8000
    depends_on:
      - db
      - minio

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    env_file: .env
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio

volumes:
  postgres_data:
  minio_data:
  minio_config:
