version: "3.2"

services:
  react-next-app:
    container_name: react-next-app
    stdin_open: true
    build:
      context: ./
      dockerfile: DockerFile
      target: production
    ports:
      - "3000:3000"
    # SSR 'client' app
    volumes:
      - .:/app
      - /app/node_modules
    command: pm2-runtime start npm --watch --name "react-next-app" -- start

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - react-next-app
