# Generated by Django 4.1 on 2022-09-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'План', 'verbose_name_plural': 'Планы'},
        ),
        migrations.AlterModelOptions(
            name='planitem',
            options={'verbose_name': 'Предмет плана', 'verbose_name_plural': 'Предметы в планах'},
        ),
        migrations.AlterField(
            model_name='plan',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='plans.planitem'),
        ),
        migrations.AlterUniqueTogether(
            name='planitem',
            unique_together={('content_type', 'object_id')},
        ),
    ]
