# Generated by Django 4.1 on 2022-09-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted_comment',
        ),
    ]
