# Generated by Django 4.1 on 2022-09-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_deleted_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
