# Generated by Django 4.1 on 2022-09-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero', models.CharField(max_length=255, verbose_name='Герой')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='RatingMPAA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=255, verbose_name='Рейтинг-MPAA')),
            ],
            options={
                'verbose_name': 'RatingMPAA',
                'verbose_name_plural': 'RatingMPAA',
            },
        ),
        migrations.CreateModel(
            name='TypeAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_content', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Type anime',
                'verbose_name_plural': 'Types anime',
            },
        ),
        migrations.CreateModel(
            name='Voiceover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voiceover', models.CharField(max_length=255, verbose_name='Озвучка')),
            ],
            options={
                'verbose_name': 'Voiceover',
                'verbose_name_plural': 'Voiceovers',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(default='0+', max_length=15, verbose_name='Возрастной рейтинг'),
        ),
        migrations.AddField(
            model_name='anime',
            name='atelier_anime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Студия'),
        ),
        migrations.AddField(
            model_name='anime',
            name='duration_series',
            field=models.CharField(max_length=255, null=True, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='anime',
            name='episode_anime',
            field=models.CharField(max_length=255, null=True, verbose_name='Количество эпизодов'),
        ),
        migrations.AddField(
            model_name='anime',
            name='next_episode',
            field=models.CharField(max_length=255, null=True, verbose_name='Следующий эпизод'),
        ),
        migrations.AddField(
            model_name='anime',
            name='original_source',
            field=models.CharField(max_length=255, null=True, verbose_name='Первоисточник'),
        ),
        migrations.AddField(
            model_name='anime',
            name='release_anime',
            field=models.CharField(max_length=255, null=True, verbose_name='Выпуск'),
        ),
        migrations.AddField(
            model_name='anime',
            name='season_anime',
            field=models.CharField(max_length=255, null=True, verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='anime',
            name='status_anime',
            field=models.CharField(choices=[('Ongion', 'Выходит последний сезон аниме'), ('Came out', 'Аниме вышло.'), ('Announcement', 'Аниме анонсированно')], default='Announcement', max_length=255, verbose_name='Статус аниме'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres_anime',
            field=models.ManyToManyField(related_name='genres_anime', to='anime.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='anime',
            name='main_heroes',
            field=models.ManyToManyField(related_name='main_heroes', to='anime.hero', verbose_name='Герои'),
        ),
        migrations.AddField(
            model_name='anime',
            name='rating_mpaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rating_mpaa', to='anime.ratingmpaa', verbose_name='Рейтинг-MPAA'),
        ),
        migrations.AddField(
            model_name='anime',
            name='type_anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type_anime', to='anime.typeanime', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='anime',
            name='voiceovers_amine',
            field=models.ManyToManyField(related_name='voiceovers_anime', to='anime.voiceover', verbose_name='Озвучка'),
        ),
    ]
