# Generated by Django 4.1 on 2022-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_genre_hero_ratingmpaa_typeanime_voiceover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Средняя оценка'),
        ),
    ]
