# Generated by Django 4.1 on 2022-09-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_alter_anime_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(blank=True, default='0+', max_length=15, null=True, verbose_name='Возрастной рейтинг'),
        ),
    ]
