# Generated by Django 4.1 on 2022-09-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_age_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='duration_series',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode_anime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество эпизодов'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='next_episode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Следующий эпизод'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='original_source',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Первоисточник'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release_anime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Выпуск'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_anime',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status_anime',
            field=models.CharField(blank=True, choices=[('Ongion', 'Выходит последний сезон аниме'), ('Came out', 'Аниме вышло.'), ('Announcement', 'Аниме анонсированно')], default='Announcement', max_length=255, verbose_name='Статус аниме'),
        ),
    ]
