# Generated by Django 4.1 on 2022-09-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_alter_anime_duration_series_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='main_heroes',
            field=models.ManyToManyField(blank=True, related_name='main_heroes', to='anime.hero', verbose_name='Герои'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='voiceovers_amine',
            field=models.ManyToManyField(blank=True, related_name='voiceovers_anime', to='anime.voiceover', verbose_name='Озвучка'),
        ),
    ]
