# Generated by Django 4.1 on 2022-09-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_anime_main_heroes_alter_anime_voiceovers_amine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres_anime',
            field=models.ManyToManyField(blank=True, related_name='genres_anime', to='anime.genre', verbose_name='Жанр'),
        ),
    ]
