# Generated by Django 4.1 on 2022-09-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_alter_anime_genres_anime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Anime', 'verbose_name_plural': 'Amine'},
        ),
    ]
