# Generated by Django 4.1 on 2022-09-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_alter_anime_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'Anime', 'verbose_name_plural': 'Anime'},
        ),
    ]
