# Generated by Django 4.1 on 2022-09-26 15:13

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_alter_anime_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(blank=True, default='0', max_length=15, null=True, verbose_name='Возрастной рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='preview',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='', verbose_name='Превью для аниме'),
        ),
    ]
