# Generated by Django 4.1 on 2022-09-27 11:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0012_alter_anime_age_rating_alter_anime_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='preview',
            field=imagekit.models.fields.ProcessedImageField(upload_to='', verbose_name='Превью для аниме'),
        ),
    ]
