# Generated by Django 4.1 on 2022-09-28 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_alter_anime_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='age_rating',
            field=models.CharField(default='0+', max_length=15, verbose_name='Возрастной рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='atelier_anime',
            field=models.CharField(max_length=255, verbose_name='Студия'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episode_anime',
            field=models.CharField(max_length=255, verbose_name='Количество эпизодов'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genres_anime',
            field=models.ManyToManyField(related_name='genres_anime', to='anime.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='release_anime',
            field=models.CharField(max_length=255, verbose_name='Выпуск'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='season_anime',
            field=models.CharField(max_length=255, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='status_anime',
            field=models.CharField(choices=[('Ongion', 'Выходит последний сезон аниме'), ('Came out', 'Аниме вышло.'), ('Announcement', 'Аниме анонсированно')], default='Announcement', max_length=255, verbose_name='Статус аниме'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='type_anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_anime', to='anime.typeanime', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='voiceovers_amine',
            field=models.ManyToManyField(related_name='voiceovers_anime', to='anime.voiceover', verbose_name='Озвучка'),
        ),
    ]
