import Head from 'next/head'
import postApi from '../app/api/posts/post.api'
import SeasonAnime from '../app/components/Home/SeasonAnime'
import NewAnime from '../app/components/Home/NewAnime'
import { NextPage } from 'next'

interface IHome {
	initialRememberValue: string
	posts: PostType[]
}

export type PostType = {
	userId: number
	id: number
	title: string
	body: string
}

export const getStaticProps = async () => {
	const [error, data] = await postApi.getAllNews()

	if (!data) {
		return {
			notFound: true
		}
	}

	return {
		props: { posts: data }
	}
}

const Home: NextPage<IHome> = ({ initialRememberValue, posts }) => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div>
				Home
				<SeasonAnime />
				<div className='container'>
					<NewAnime />
				</div>
			</div>
		</>
	)
}

// Home.getInitialProps = ({ req }) => {
//   const cookies = parseCookies(req)
//
//   return {
//     initialRememberValue: cookies.rememberMe
//   }
// }

export default Home
