import { NextPage } from 'next'
import Head from 'next/head'

const Music: NextPage = () => {
    return (
        <>
            <Head>
                <title>Music</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                Music
            </div>
        </>
    )
}

export default Music
